name: cymbal_bank_l_o_a_n_a_p_p
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_size_text: 3.0.0
  cached_network_image: 3.4.1
  collection: ^1.19.1
  dropdown_button2: 2.3.9
  equatable: ^2.0.7
  file_picker: ^10.3.1
  firebase_core: ^4.0.0
  flutter_animate: ^4.5.2
  flutter_cache_manager: 3.4.1
  flutter_svg: ^2.2.0
  font_awesome_flutter: ^10.9.0
  from_css_color: 2.0.0
  go_router: ^16.1.0
  google_fonts: ^6.3.0
  http: 1.2.2
  image_picker: 1.1.2
  intl: ^0.20.2
  json_path: ^0.7.6
  mime_type: ^1.0.1
  page_transition: ^2.2.1
  path_provider: ^2.1.5
  provider: ^6.1.5
  rxdart: ^0.28.0
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  timeago: ^3.7.1
  url_launcher: ^6.3.2
  video_player: ^2.10.0
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_lints: ^6.0.0
  lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/jsons/
